# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Studies in logic, math, and CS.
email: alfonso.higuera.gamboa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I want to fortify my understanding of fundamentals underlying
  Software Engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alfonso-higuera.github.io" # the base hostname & protocol for your site
twitter_username: alfhiggam
github_username:  alfonso-higuera

# Build settings
markdown: kramdown
